project:
  type: website
  title: "User Interfaces (UIs) in Python"
  output-dir: "_site"
  
website:
  title: "User Interfaces (UIs) in Python"
  description: "CLI, TUI and Web UIs in Python: Click, Typer, Fire, docopt, Rich, tqdm, Flask, Streamlit."
  site-url: "https://your-site-url.com"
  repo-url: "https://github.com/jfimbett/UserInterfacesPython"
  
  navbar:
    title: "UIs in Python"
    left:
      - text: "Home"
        href: index.html
      - text: "Course Days"
        menu:
          - text: "UI Slide Deck"
            href: user_interfaces_python.qmd
    right:
      - icon: github
        href: "https://github.com/jfimbett/UserInterfacesPython"

format:
  html:
    theme: 
      - cosmo
      - src/assets/styles.css # where custom styles are located
    toc: true
    toc-depth: 3
    number-sections: true
    number-depth: 3
    code-fold: false
    code-tools: true
    citations-hover: true
    footnotes-hover: true
    
  revealjs:
    theme: white
    css: src/assets/styles.css
    slide-number: true
    chalkboard: true
    preview-links: auto
    transition: slide
    background-transition: fade
    hash-type: number
    controls: true
    progress: true
    center: false
    
execute:
  freeze: auto
  cache: true

editor: visual
